---
title: "awf-cieszczyk-drd2"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


```{r eval=FALSE, include=FALSE}
install.packages("readxl")
install.packages("dplyr")
install.packages("stringr")
install.packages("HardyWeinberg")
# install.packages("kableExtra")
```

```{r message=FALSE}
library(readxl)
library(stringr)
library(dplyr)
library(HardyWeinberg)
library(knitr)
```


### Wczytanie danych

Wejściowy arkusz został nieco zmodyfikowany - usunięte scalenia komórek

```{r, message=FALSE}
raw_data <- read_excel('wyniki-DRD2-unmerged-header.xls')
subheader <- raw_data[1, ]

numeric_cols <- unname(!is.na(subheader))[1, ]
merged_header <- colnames(subheader)[numeric_cols]
merged_header <- str_replace(merged_header, '\\.{3}\\d{1,2}', '')
new_cols <- paste0(merged_header, c('_przed', '_po'))
colnames(raw_data)[numeric_cols] <- new_cols

data <- read_excel('wyniki-DRD2-unmerged-header.xls', skip=1)
colnames(data) <- colnames(raw_data)
data %>% 
  mutate(id=paste(`Nr`, `Lp.`, sep='_')) ->
  data

data
```

### Hardy-Weinberg equilibrium

```{r}
(rses <- str_subset(colnames(data), "rs"))
genotypes <- list(
  "DRD2 rs1076560" = c("CC", "C/A", "AA"),
  "DRD2 rs1076560" = c("CC", "C/A", "AA"),
  "DRD2 rs12364283" = c("GG", "G/A", "AA"),
  "DRD2 rs1799732" = c("--", "C (-)", "CC"),
  "DRD2 rs1800497" = c("CC", "C/T", "TT"),
  "DRD2 rs1800498" = c("CC", "C/T", "TT")
)

pvals <- numeric()
for (rs_name in names(genotypes)) {
  rs <- factor(pull(data, rs_name), levels = genotypes[[rs_name]])
  stopifnot(!is.na(rs))
  genotype_counts <- table(rs)
  X <- as.vector(genotype_counts)
  names(X) <- c("AA", "AB", "BB")
  result <- HWChisq(X, verbose = FALSE)
  pvals <- c(pvals, result$pval)
}
```

```{r}
tibble(rs = names(genotypes), p = pvals)
```

